version: "3"

volumes:
  produtosdata:

networks:
  backend:

services:

 mysql:
   image: "mysql:latest"
   volumes:
     - produtosdata:/var/lib/mysql
     - ./_MySQL_init_Script:/docker-entrypoint-initdb.d
   networks:
     - backend
   environment:
     - MYSQL_ROOT_PASSWORD=luiz@1234
     - bind-address=0.0.0.0
 mvc:
   build:
     context: .
     dockerfile: Dockerfile.multi
   networks:
     - backend
   ports:
     - 5000:80
   environment:
     - DBHOST=mysql
   depends_on:
     - mysql
