#Estagio 1 - base
FROM mcr.microsoft.com/dotnet/sdk:3.1 AS base
RUN mkdir /app
WORKDIR /app/
EXPOSE 80/tcp

#Estagio 2 - publish
FROM mcr.microsoft.com/dotnet/sdk:3.1 AS publish
WORKDIR /app/
COPY mvc.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o dist

#Estagio 3 - final
FROM base AS final
WORKDIR /dist/
COPY --from=publish /app/dist .
LABEL version="1.1" description="APP Net Core"
ENV ASPNETCORE_URLS=http://+:80 
ENTRYPOINT ["dotnet", "mvc.dll"]

